### ISSUE TITLE
TimeFlex not setting swid when creating a new user

### ISSUE THREAD

**Issue by TheRasPiGuy** [Times-0/TimeFlex#3]
Creating a new user doesn't set the swid, giving me an error in the console:
`OperationalError: (_mysql_exceptions.OperationalError) (1048, "Column 'swid' cannot be null")`

**Comment by valid22** [comment]
Update your `Penguins` table's `swid` column property, you can do so by using the following SQL query

```sql
ALTER TABLE `penguins` MODIFY swid char(38) NULL;
```

**Comment by TheRasPiGuy** [comment]
> Update your `Penguins` table's `swid` column property, you can do so by using the following SQL query
> 
> ```sql
> ALTER TABLE `penguins` MODIFY swid char(38) NULL;
> ```

Doing this just gives me way more errors in the console, and doesn't let me do anything because my player's swid is null, making TimeFlex return null for coins, friends, avatar, etc.
Basically, it just won't automatically assign an swid, and making the swid column null in the sql database completely breaks it

**Comment by TheRasPiGuy** [comment]
Ok, so I fix the issue by setting the swid column as null like you said, and then changing Flex.py's line 166 from this:
`user = Penguin(username=uname, password='firebase', email=userData.email, nickname='-_-')`
to this:
`user = Penguin(username=uname, password='firebase', swid=userData_['uid'], email=userData.email, nickname='-_-')`
which sets the swid as the player's firebase uid, which can be found in firebase project -> authentication -> users -> User UID

although now for whatever reason, none of the swf files are loading, which I'll look at later
